// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissaoBackend.Data;

#nullable disable

namespace MissaoBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831071250_AdicionarAutorCanticoUmbLatKmb")]
    partial class AdicionarAutorCanticoUmbLatKmb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MissaoBackend.Models.Cantico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("longtext");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TopicoId");

                    b.ToTable("Canticos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoKmb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("longtext");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TopicoId");

                    b.ToTable("CanticosKmb");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoLat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("longtext");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TopicoId");

                    b.ToTable("CanticosLat");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoUmb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("longtext");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TopicoId");

                    b.ToTable("CanticosUmb");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoLat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CatecismoLatTopicoId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatecismoLatTopicoId");

                    b.ToTable("CatecismosLat");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoLatTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CatecismoLatTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoOtc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CatecismoOtcTopicoId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatecismoOtcTopicoId");

                    b.ToTable("CatecismosOtc");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoOtcTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CatecismoOtcTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CatecismoPtTopicoId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatecismoPtTopicoId");

                    b.ToTable("CatecismosPt");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPtTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CatecismoPtTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CatecismoUbTopicoId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatecismoUbTopicoId");

                    b.ToTable("CatecismosUb");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUbTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CatecismoUbTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.ConfiguracaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("ConfiguracaoSistema");
                });

            modelBuilder.Entity("MissaoBackend.Models.Encomenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Morada")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PercentualComissaoAplicado")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorComissao")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Encomendas");
                });

            modelBuilder.Entity("MissaoBackend.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao");

                    b.Property<string>("Leituras")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "leituras");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "observacoes");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "titulo");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("MissaoBackend.Models.Ficheiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Dados")
                        .IsRequired()
                        .HasColumnType("LONGBLOB");

                    b.HasKey("Id");

                    b.ToTable("Ficheiros");
                });

            modelBuilder.Entity("MissaoBackend.Models.FormaApoio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FormasApoio");
                });

            modelBuilder.Entity("MissaoBackend.Models.FormaPagamentoLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Detalhe")
                        .HasColumnType("longtext");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("FormasPagamentoLoja");
                });

            modelBuilder.Entity("MissaoBackend.Models.Gestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("MissaoBackend.Models.ItemEncomenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EncomendaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EncomendaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensEncomenda");
                });

            modelBuilder.Entity("MissaoBackend.Models.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aprovada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InfoPagamento")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Morada")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PercentualComissao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("MissaoBackend.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EmDestaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecoPromocional")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("MissaoBackend.Models.Topico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Topicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoKmb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TopicoKmb", (string)null);
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoLat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TopicosLat");
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoUmb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TopicoUmb", (string)null);
                });

            modelBuilder.Entity("MissaoBackend.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Baptismo")
                        .HasColumnType("longtext");

                    b.Property<string>("Casamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Comunhao")
                        .HasColumnType("longtext");

                    b.Property<string>("Crisma")
                        .HasColumnType("longtext");

                    b.Property<string>("Diocese")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nascimento")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ordem")
                        .HasColumnType("longtext");

                    b.Property<string>("Paroquia")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("MissaoBackend.Models.Cantico", b =>
                {
                    b.HasOne("MissaoBackend.Models.Topico", "Topico")
                        .WithMany()
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoKmb", b =>
                {
                    b.HasOne("MissaoBackend.Models.TopicoKmb", "Topico")
                        .WithMany("Canticos")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoLat", b =>
                {
                    b.HasOne("MissaoBackend.Models.TopicoLat", "Topico")
                        .WithMany("Canticos")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoUmb", b =>
                {
                    b.HasOne("MissaoBackend.Models.TopicoUmb", "Topico")
                        .WithMany("Canticos")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoLat", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoLatTopico", "CatecismoLatTopico")
                        .WithMany("CatecismosLat")
                        .HasForeignKey("CatecismoLatTopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatecismoLatTopico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoOtc", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoOtcTopico", "CatecismoOtcTopico")
                        .WithMany("CatecismosOtc")
                        .HasForeignKey("CatecismoOtcTopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatecismoOtcTopico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPt", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoPtTopico", "CatecismoPtTopico")
                        .WithMany("CatecismosPt")
                        .HasForeignKey("CatecismoPtTopicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CatecismoPtTopico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPtTopico", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoPtTopico", "Parent")
                        .WithMany("SubTopicos")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUb", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoUbTopico", "CatecismoUbTopico")
                        .WithMany("CatecismosUb")
                        .HasForeignKey("CatecismoUbTopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatecismoUbTopico");
                });

            modelBuilder.Entity("MissaoBackend.Models.Encomenda", b =>
                {
                    b.HasOne("MissaoBackend.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MissaoBackend.Models.FormaPagamentoLoja", b =>
                {
                    b.HasOne("MissaoBackend.Models.Loja", "Loja")
                        .WithMany("FormasPagamento")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MissaoBackend.Models.ItemEncomenda", b =>
                {
                    b.HasOne("MissaoBackend.Models.Encomenda", "Encomenda")
                        .WithMany("Itens")
                        .HasForeignKey("EncomendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissaoBackend.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encomenda");
                });

            modelBuilder.Entity("MissaoBackend.Models.Produto", b =>
                {
                    b.HasOne("MissaoBackend.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoLatTopico", b =>
                {
                    b.Navigation("CatecismosLat");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoOtcTopico", b =>
                {
                    b.Navigation("CatecismosOtc");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPtTopico", b =>
                {
                    b.Navigation("CatecismosPt");

                    b.Navigation("SubTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUbTopico", b =>
                {
                    b.Navigation("CatecismosUb");
                });

            modelBuilder.Entity("MissaoBackend.Models.Encomenda", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MissaoBackend.Models.Loja", b =>
                {
                    b.Navigation("FormasPagamento");
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoKmb", b =>
                {
                    b.Navigation("Canticos");
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoLat", b =>
                {
                    b.Navigation("Canticos");
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoUmb", b =>
                {
                    b.Navigation("Canticos");
                });
#pragma warning restore 612, 618
        }
    }
}
