// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissaoBackend.Data;

#nullable disable

namespace MissaoBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517220132_AdicionarSubtopicosCatecismo")]
    partial class AdicionarSubtopicosCatecismo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MissaoBackend.Models.Cantico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TopicoId");

                    b.ToTable("Canticos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoUmb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TopicoId");

                    b.ToTable("CanticosUmb");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CatecismoPtTopicoId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatecismoPtTopicoId");

                    b.ToTable("CatecismosPt");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPtTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CatecismoPtTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CatecismoUbTopicoId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatecismoUbTopicoId");

                    b.ToTable("CatecismosUb");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUbTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CatecismoUbTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao");

                    b.Property<string>("Leituras")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "leituras");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "observacoes");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "titulo");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("MissaoBackend.Models.Gestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("MissaoBackend.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoLonga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MissaoBackend.Models.Topico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Topicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoUmb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TopicoUmb", (string)null);
                });

            modelBuilder.Entity("MissaoBackend.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Baptismo")
                        .HasColumnType("longtext");

                    b.Property<string>("Casamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Catequese")
                        .HasColumnType("longtext");

                    b.Property<string>("CentroMissionario")
                        .HasColumnType("longtext");

                    b.Property<string>("Comunhao")
                        .HasColumnType("longtext");

                    b.Property<string>("Crisma")
                        .HasColumnType("longtext");

                    b.Property<string>("Diocese")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nascimento")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ordem")
                        .HasColumnType("longtext");

                    b.Property<string>("Paroquia")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("MissaoBackend.Models.Cantico", b =>
                {
                    b.HasOne("MissaoBackend.Models.Topico", "Topico")
                        .WithMany()
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CanticoUmb", b =>
                {
                    b.HasOne("MissaoBackend.Models.TopicoUmb", "Topico")
                        .WithMany("Canticos")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPt", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoPtTopico", "CatecismoPtTopico")
                        .WithMany("CatecismosPt")
                        .HasForeignKey("CatecismoPtTopicoId");

                    b.Navigation("CatecismoPtTopico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPtTopico", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoPtTopico", "Parent")
                        .WithMany("SubTopicos")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUb", b =>
                {
                    b.HasOne("MissaoBackend.Models.CatecismoUbTopico", "CatecismoUbTopico")
                        .WithMany("CatecismosUb")
                        .HasForeignKey("CatecismoUbTopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatecismoUbTopico");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoPtTopico", b =>
                {
                    b.Navigation("CatecismosPt");

                    b.Navigation("SubTopicos");
                });

            modelBuilder.Entity("MissaoBackend.Models.CatecismoUbTopico", b =>
                {
                    b.Navigation("CatecismosUb");
                });

            modelBuilder.Entity("MissaoBackend.Models.TopicoUmb", b =>
                {
                    b.Navigation("Canticos");
                });
#pragma warning restore 612, 618
        }
    }
}
